variable "vpc_cidr" {}
variable "pub_sbn_1a_cidr" {}
variable "pub_sbn_1b_cidr" {}
variable "php_srv_ami" {}
variable "php_srv_ins_type" {}
variable "php_srv_ssh_ing_cidr" {}
variable "php_srv_ssh_egr_cidr" {}
variable "php_srv_http_ing_cidr" {}
variable "php_srv_http_egr_cidr" {}
variable "rds_ing_cidr" {}
variable "rds_egr_cidr" {}
variable "rds_master_username" {}
variable "rds_master_password" {}
variable "rds_database_name" {}
variable "rds_instance_class" {}
variable "rds_cluster_identifier" {}
variable "rds_instance_identifier" {}
variable "rds_publicly_accessible" {}
variable "rds_name_pub_sbn_grp" {}